import {accordion} from './accordion.js';
import {popup} from './popup.js';
import {scroll} from './scroll.js';
import {slider} from './slider.js';
import {fetchData} from './fetch.js';
accordion();
popup();
scroll();
slider();
fetchData();
